apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: movie-catalog-service
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dev
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: .k8s/overlays/dev/
    repoURL: https://github.com/utsabroy/movie-catalog-service
    targetRevision: eks-kustomize